import React from 'react';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from './lib/AntdRegistry';
import { NextAuthProvider } from '@/app/lib/nextAuthProvider';
// import '@/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <NextAuthProvider>
        <StyledComponentsRegistry>
          {children}
        </StyledComponentsRegistry>
      </NextAuthProvider>
    </body>
  </html>
);

export default RootLayout;